/*
 * Microservicio de Contenido - UnderSounds
 *
 * Este microservicio gestiona el contenido multimedia y comercial del proyecto \"UnderSounds\", incluyendo albumes, canciones, generos, merchandising y noticias musicales.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"contenido/db"
	sw "contenido/go"
	"log"
)

func main() {
	db.InitDatabase()
	defer db.DB.Close()
	routes := sw.ApiHandleFunctions{
		AlbumesAPI:       sw.AlbumesAPI{DB: db.DB},
		MerchandisingAPI: sw.MerchandisingAPI{DB: db.DB},
		PedidoAPI:        sw.PedidoAPI{DB: db.DB},
		SearchAPI:        sw.SearchAPI{DB: db.DB},
	}

	log.Printf("Servidor iniciado")

	router := sw.NewRouter(routes)

	// Servir archivos estáticos desde la carpeta uploads
	router.Static("/uploads", "./uploads")

	log.Fatal(router.Run(":8080"))
}
