/*
 * Microservicio de Contenido - UnderSounds
 *
 * Este microservicio gestiona el contenido multimedia y comercial del proyecto \"UnderSounds\", incluyendo albumes, canciones, generos, merchandising y noticias musicales.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"github.com/gin-gonic/gin"
)

type CancionesAPI struct {
}

// Get /canciones
// Listar todas las canciones 
func (api *CancionesAPI) CancionesGet(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// Delete /canciones/:id
// Eliminar una cancion 
func (api *CancionesAPI) CancionesIdDelete(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// Get /canciones/:id
// Obtener detalles de una cancion 
func (api *CancionesAPI) CancionesIdGet(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// Patch /canciones/:id
// Actualizar datos de una cancion 
func (api *CancionesAPI) CancionesIdPatch(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// Get /canciones/:id/verAutores
// Obtener los artista de una cancion 
func (api *CancionesAPI) CancionesIdVerAutoresGet(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// Post /canciones
// Crear una nueva cancion 
func (api *CancionesAPI) CancionesPost(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

