/*
 * Microservicio de Contenido - UnderSounds
 *
 * Este microservicio gestiona el contenido multimedia y comercial del proyecto \"UnderSounds\", incluyendo albumes, canciones, generos, merchandising y noticias musicales.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"github.com/gin-gonic/gin"
)

type MerchandisingAPI struct {
}

// Get /merch
// Listar todos los productos de merchandising 
func (api *MerchandisingAPI) MerchGet(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// Delete /merch/:id
// Eliminar un producto 
func (api *MerchandisingAPI) MerchIdDelete(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// Patch /merch/:id/disminuirStockMerch
// Disminuir la cantidad disponible de un producto 
func (api *MerchandisingAPI) MerchIdDisminuirStockMerchPatch(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// Get /merch/:id
// Obtener un producto de merchandising 
func (api *MerchandisingAPI) MerchIdGet(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// Patch /merch/:id
// Actualizar un producto 
func (api *MerchandisingAPI) MerchIdPatch(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// Patch /merch/:id/recargarStockMerch
// Aumentar la cantidad disponible de un producto 
func (api *MerchandisingAPI) MerchIdRecargarStockMerchPatch(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// Post /merch
// Crear un nuevo producto de merchandising 
func (api *MerchandisingAPI) MerchPost(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

