/*
 * Microservicio de Contenido - UnderSounds
 *
 * Este microservicio gestiona el contenido multimedia y comercial del proyecto \"UnderSounds\", incluyendo albumes, canciones, generos, merchandising y noticias musicales.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type Merch struct {

	Id int32 `json:"id,omitempty"`

	Nombre string `json:"nombre"`

	Precio float32 `json:"precio"`

	UrlImagen string `json:"urlImagen"`

	Artista int32 `json:"artista"`

	Stock int32 `json:"stock"`
}
