/*
 * Microservicio de Contenido - UnderSounds
 *
 * Este microservicio gestiona el contenido multimedia y comercial del proyecto \"UnderSounds\", incluyendo albumes, canciones, generos, merchandising y noticias musicales.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type VerAutoresCancion struct {

	// ID de la cancion
	IdCancion int32 `json:"idCancion"`

	Artistas []int32 `json:"artistas"`
}
